# Generated by Django 3.2.8 on 2021-12-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='poster_url',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='book',
            name='is_book_club',
            field=models.BooleanField(default=False),
        ),
    ]
