# Generated by Django 3.2.8 on 2021-12-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='posts',
        ),
    ]
